### ISSUE TITLE
Pls add a linux port

### ISSUE THREAD

**Issue by livingHuman1206** [landoodle123/ThingsToDoPRO#3]
i use linux, please add a linux port

**Comment by landoodle123** [comment]
no

**Comment by livingHuman1206** [comment]
:(

**Comment by 10minecraft29** [comment]
ArchLinux user?

**Comment by landoodle123** [comment]
imagine using arch in 2025, id much rather compile the linux kernel from source and create my own distro

**Comment by livingHuman1206** [comment]
oh hell no im not an arch user, i use debian with kde plasma

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/eaa135f3-ac70-4ddd-8eaa-007cff67f44d" />
